### ISSUE TITLE
MatBlazor 1.6.1 Microsoft.JSInterop.JSException: iconRef is not defined

### ISSUE THREAD

**Issue by gitbugreport** [SamProf/MatBlazor#199]
ReferenceError: iconRef is not defined
    at Object.e.init (https://localhost:5001/EmbeddedBlazorFile/dist/matBlazor.js:1:680669)
    at https://localhost:5001/_framework/blazor.server.js:8:28347
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:28316)
    at https://localhost:5001/_framework/blazor.server.js:1:19148
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:19119)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (https://localhost:5001/_framework/blazor.server.js:1:38027)
   at Microsoft.JSInterop.JSRuntimeBase.InvokeWithDefaultCancellation[T](String identifier, IEnumerable`1 args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
warn: Microsoft.AspNetCore.Components.Web.Rendering.RemoteRenderer[100]
      Unhandled exception rendering component: iconRef is not defined

**Comment by gitbugreport** [comment]
Hmm, it is working after cleaning project and build again.

**Comment by SamProf** [comment]
This bug was maybe in 1.6.0. 
But in 1.6.1 should be fixed.

**Comment by SamProf** [comment]
We can add nocache parameter for server side Blazor to avoid this problem.
