### ISSUE TITLE
MatSelect - Enhanced mode error

### ISSUE THREAD

**Issue by AyronK** [SamProf/MatBlazor#217]
MatSelect does not work once "Enhanced" mode is active `Enhanced="@true"`. It works fine when it's disabled or set `false`, though.

**Error**:
```
Microsoft.JSInterop.JSException: Cannot read property 'classList' of null
TypeError: Cannot read property 'classList' of null
    at Object.hasClass (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:410051)
    at c.init (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:51584)
    at p.a (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:12704)
    at new p (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:412111)
    at u.t [as menuSurfaceFactory_] (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:108528)
    at u.initialSyncWithDOM (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:108731)
    at u.a (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:12716)
    at new u (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:112149)
    at i (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:395178)
    at y.enhancedSelectSetup_ (http://localhost:5000/EmbeddedBlazorFile/dist/matBlazor.js:1:401887)
   at Microsoft.JSInterop.JSRuntimeBase.InvokeWithDefaultCancellation[T](String identifier, IEnumerable`1 args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
warn: Microsoft.AspNetCore.Components.Web.Rendering.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot read property 'classList' of null
```

**Blazor**: 3.0.0-preview8.19405.7
**MatBlazor**: 1.6.3

**Comment by AyronK** [comment]
Works fine in the latest version

**Comment by khenzar** [comment]
I am getting very similar error in 2.2.0 :
![image](https://user-images.githubusercontent.com/2130285/76785288-79e4ca00-67b5-11ea-9d94-561bff8bdb2a.png)
