### ISSUE TITLE
Could not load file or assembly 'MatBlazor, Version=1.8.0.0 after .Net 3.0 Update

### ISSUE THREAD

**Issue by unencode** [SamProf/MatBlazor#263]
After updating to .Net 3.0 (SDK 3.0.100 x64) the application builds but when starting up presents this error below.

Specifically, I updated:

.Net 3.0 (SDK 3.0.100 x64)
Visual Studio 2019 16.3.0
Blazor/ .Net NuGets to .Net 3.0 versions Nugets screen cap here: https://i.imgur.com/GQJGGRT.png

Console output:
```

Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'MatBlazor, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'MatBlazor, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
   at Portal.ServerSide.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()


crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
System.IO.FileLoadException: Could not load file or assembly 'MatBlazor, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'MatBlazor, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
   at Portal.ServerSide.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()

```

Startup.cs Line 106 where the exception occurs is:

` app.UseEmbeddedBlazorContent(typeof(MatBlazor.BaseMatComponent).Assembly);`

**Comment by unencode** [comment]
SOLVED.
After deleting bin and obj folders, things worked properly.
