### ISSUE TITLE
IMatToaster.Add should be thread-safe

### ISSUE THREAD

**Issue by maxreb** [SamProf/MatBlazor#350]
Using ASP.Net Core 3 Server Side Blazor (Razor Components) with MatBlazor 1.9.0

When I try to add a new toaster in an asynchronous way (in my example it's an event handler) it can happen, that the call throws an `InvalidOperationException: Collection was modified; enumeration operation may not execute.` This is likely because the `Add` call tries to access a collection in a foreach loop which was modified in another thread. Unluckily it's hard to repeat this error as it could happen, but does not have to happen. 

The full stack-trace (with "Debugging my code only" on :/ )

> Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at MatBlazor.MatToaster.Add(String message, MatToastType type, String title, String icon, Action`1 configure)
>    at XXX.Components.Map.GISComponentBase.Mqtt_OnNewOnNewSensorDataRX(Object sender, SensorData e) in d:\...\Components\Map\GISComponent.razor.cs:line 172
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Christian-Oleson** [comment]
@maxreb ,
This issue should now be resolved in the latest MatBlazor version. Can you confirm this?
