### ISSUE TITLE
Matblazor Select Null value

### ISSUE THREAD

**Issue by lkmcelik** [SamProf/MatBlazor#372]
is there any way to binding matselect to null value
this is working
`  <select class="mdc-select__native-control" @bind="SecilenAtikGrubu.GrupId">
                        @foreach (var item in TumAtikTipleri)
                        {
                            <option value="@item.Id">@item.Deger1</option>
                        }
                    </select>`
but this is not
` <MatSelect Label="Atık Tipi" @bind-Value="@SecilenAtikGrubu.GrupId" Style="width:100%">
                        @foreach (var item in TumAtikTipleri)
                        {
                            <MatOption Value="@item.Id">@item.Deger1</MatOption>
                        }
                    </MatSelect>`

and this is the binding class
` public class GrupKodlari
 {
[Key]
public int Id { get; set; }
public string Tur { get; set; }
public string Isim { get; set; }
public string Deger1 { get; set; }
public string Deger2 { get; set; }
public string Deger3 { get; set; }
public int? GrupId { get; set; } 
public virtual GrupKodlari Grup { get; set; }
}`

**Comment by dinonovak** [comment]
Also facing the same issue. If MatSelect is bound to database and bound filed has NULL value, it is creating the error
System.NullReferenceException: Object reference not set to an instance of an object.
   at MatBlazor.MatOptionTypeKey`2.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'sNPCplRtxjwzTlBAf1YCDGmgsWBvBOt5hX13R9wCQ7Q'.


This is how items are added to MatSelect
```
@foreach (var item in itemList)
{
        <MatOption TValue="int" Value="@item.id">@item.Title</MatOption>
}
```
Here is the

**Comment by dinonovak** [comment]
Any update or I need to migrate to StringSelect ?

**Comment by lindespang** [comment]
Hi! Thanks for using MatBlazor.
I just tried it out myself and I could bind to a null value without issues, maybe this is an issue that has been solved in recent releases.

If you still have a problem with this, can you please provide an example on www.blazorfiddle.com ?

**Comment by lindespang** [comment]
Closing due to inactivity. Please reopen if this is still a problem for you.
