### ISSUE TITLE
MatSelect issue on Master branch

### ISSUE THREAD

**Issue by ctrl-alt-d** [SamProf/MatBlazor#380]
I told @enkodellc about to [write a demo-sample for `ValueChanged`'s matSelect](https://stackoverflow.com/a/59547035/842935). Now, after clone master repo branch and run demo ( `src/MatBlazor.Demo.ServerApp/MatBlazor.Demo.ServerApp.csproj` ) without any change, an error appear on MatSelect component:

```
[2020-01-04T16:49:13.230Z] Error: Microsoft.JSInterop.JSException: MDCSelect: Missing required element: The following selector must be present: '.mdc-select__selected-text'
Error: MDCSelect: Missing required element: The following selector must be present: '.mdc-select__selected-text'
    at y.initialize (https://localhost:5001/_content/MatBlazor/dist/matBlazor.js:1:193359)
    at y.a (https://localhost:5001/_content/MatBlazor/dist/matBlazor.js:1:8390)
    at new y (https://localhost:5001/_content/MatBlazor/dist/matBlazor.js:1:201334)
    at new t (https://localhost:5001/_content/MatBlazor/dist/matBlazor.js:1:191330)
    at Object.e.init (https://localhost:5001/_content/MatBlazor/dist/matBlazor.js:1:190884)
    at https://localhost:5001/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:31390)
    at https://localhost:5001/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args) in /tmp/s/MatBlazor/src/MatBlazor/Components/Base/BaseMatComponent.cs:line 83
   at MatBlazor.BaseMatSelectTypeKey`2.<.ctor>b__3_5() in /tmp/s/MatBlazor/src/MatBlazor/Components/MatSelect/BaseMatSelectTypeKey.cs:line 41
   at MatBlazor.BaseMatComponent.OnAfterRenderAsync(Boolean firstRender) in /tmp/s/MatBlazor/src/MatBlazor/Components/Base/BaseMatComponent.cs:line 43
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

![MatBlazor - Material Design components for Blazor - Google Chrome_717](https://user-images.githubusercontent.com/3105983/71768848-9abdb300-2f1a-11ea-9240-eaf9ffac6a2f.png)

Other components (TextFiel, Slider, RadioButton, ... ) are running without issues.

I write the issue just to notify it. Congrats about your great project.

**Comment by LuisAraya07** [comment]
Hi, did you fix it? i have the same issue

**Comment by enkodellc** [comment]
This issue seems to be resolved from the stackoverflow answer and I cannot recreate with the latest version of the MatBlazor demo. Please close if this issue is resolved. Thanks,

**Comment by Christian-Oleson** [comment]
@ctrl-alt-d @enkodellc ,
Can this be closed?
