### ISSUE TITLE
MatBlazor.Web fails to build due to SCSS errors

### ISSUE THREAD

**Issue by frankhale** [SamProf/MatBlazor#512]
Node version 14.0.0
OS: Windows 10

Trying to run a `npm run build` to produce the CSS and JS. I have not made any modifications. I downloaded the code and did a `npm install` and then `npm run build`.

```
C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web>npm run build

> matblazor-web@1.0.0 build C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web
> webpack --config webpack/prod.config.js

Hash: 88874c9cf343f22ec4ba
Version: webpack 4.43.0
Time: 7826ms
Built at: 04/26/2020 7:33:10 PM
 1 asset
Entrypoint matBlazor = matBlazor.js
 [38] ./src/matButton/matButton.js 1.42 KiB {0} [built]
 [68] ./src/matMenu/matMenu.js 1.86 KiB {0} [built]
 [85] ./src/matRipple/matRipple.js 233 bytes {0} [built]
 [89] ./src/utils/utils.js 273 bytes {0} [built]
 [94] multi ./src/main.js ./src/main.scss 40 bytes {0} [built]
 [95] ./src/main.js 4.92 KiB {0} [built]
 [96] ./src/matCheckbox/matCheckbox.js 794 bytes {0} [built]
[100] ./src/matTextField/matTextField.js 555 bytes {0} [built]
[109] ./src/matNumericUpDownField/matNumericUpDownField.js 1.01 KiB {0} [built]
[110] ./src/matRadioButton/matRadioButton.js 728 bytes {0} [built]
[113] ./src/matSelect/matSelect.js 2.38 KiB {0} [built]
[121] ./src/matSlider/matSlider.js 870 bytes {0} [built]
[124] ./src/matSlideToggle/matSlideToggle.js 1.46 KiB {0} [built]
[127] ./src/matCard/matCard.js 137 bytes {0} [built]
[193] ./src/main.scss 1.45 KiB {0} [built] [failed] [1 error]
    + 179 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
        on line 24 of node_modules/@material/theme/mdc-theme.scss
        from line 2 of C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\src\main.scss
>> @include mixins.core-styles;

   ---------^

    at C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.callback (C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\sass-loader\dist\index.js:73:7)
    at Object.done [as callback] (C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\neo-async\async.js:8067:18)
    at options.error (C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\node_modules\node-sass\lib\index.js:294:32)
 @ multi ./src/main.js ./src/main.scss matBlazor[1]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--6-2!src/main.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--6-2!./src/main.scss 416 bytes {0} [built] [failed] [1 error]

    ERROR in ./src/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--6-2!./src/main.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
            on line 24 of node_modules/@material/theme/mdc-theme.scss
            from line 2 of C:\Users\frank\Downloads\MatBlazor-master\src\MatBlazor.Web\src\main.scss
    >> @include mixins.core-styles;

       ---------^

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! matblazor-web@1.0.0 build: `webpack --config webpack/prod.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the matblazor-web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frank\AppData\Roaming\npm-cache\_logs\2020-04-26T23_33_10_707Z-debug.log
```

**Comment by frankhale** [comment]
Dupe of https://github.com/SamProf/MatBlazor/issues/479
