### ISSUE TITLE
MatMenu in 2.6 throwing JS exception: Could not find 'setAnchorElement'

### ISSUE THREAD

**Issue by whentotrade** [SamProf/MatBlazor#556]
**Describe the bug**
Using the MatMenu in 2.3 as proposed by the docs, all was working. When upgrading to 2.6 from 2.3, JS interop now throws an exception:

```
Microsoft.JSInterop.JSException: Could not find 'setAnchorElement' in 'window.matBlazor.matMenu'.
Error: Could not find 'setAnchorElement' in 'window.matBlazor.matMenu'.
    at http://localhost:5000/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (http://localhost:5000/_framework/blazor.server.js:8:30709)
    at http://localhost:5000/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:8:31390)
    at http://localhost:5000/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:5000/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
```

**Comment by whentotrade** [comment]
I dont know why, but was related to some caching issues in my build. With clean rebuild, the error was gone.
