### ISSUE TITLE
MatSelect enum problem

### ISSUE THREAD

**Issue by Odis25** [SamProf/MatBlazor#709]
Hello,
I try to use enum type with MatSelect:

**Blazorfiddle link**
```
<MatSelect @bind-Value="@Command.HardwareType">
         <MatOption TValue="HardwareType" Value="HardwareType.PLC">PLC</MatOption>
</MatSelect>
```
and it gives me some null reference error:
```
[2020-09-09T14:18:17.445Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at MatBlazor.BaseCoreMatOption`1.StringValue()
   at MatBlazor.CoreMatOption`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
e.log @ blazor.server.js:19
blazor.server.js:1 [2020-09-09T14:18:17.447Z] Information: Connection disconnected.
```
Could you please tell me where did  i mistaken?

**Comment by Odis25** [comment]
Problem solved by using MatItemSelect.
