### ISSUE TITLE
MatFileUpload doesn't work in IE11- The JSON value could not be converted to System.DateTime

### ISSUE THREAD

**Issue by danikf** [SamProf/MatBlazor#755]
Hi, 
1) thank you for your work!
2) the issue: Uploading of file ends with error in IE11 (rest of the aplication works correctly with appropriate polyfills). (server side blazor of course :-)

**Reproduce:** Try to upload file in IE11 with MatFileUpload, no additional code needed, no need to hook OnChange callback.

**Error reason:**
IE is not compatible with new Date(json-string-date-format) construct. Some tweak of matFileUpload.ts will suppress the error
* Throws error: `lastModified: new Date(file.lastModified)`
* Is OK (just for test): `lastModified: new Date(2012, 11, 2, 19, 30, 0)`

**Error from IE11:**
Unhandled promise rejection Error: Error: System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $[0].lastModified | LineNumber: 0 | BytePositionInLine: 28.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Error: System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $[0].lastModified | LineNumber: 0 | BytePositionInLine: 28.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at S",
      message: "Error: System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $[0].lastModified | LineNumber: 0 | BytePositionInLine: 28.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at S",
      name: "Error",
      stack: "Error: Error: System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $[0].lastModified | LineNumber: 0 | BytePositionInLine: 28.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
",
      Symbol()_7.z7zpveqqigq: undefined,
      Symbol()_h.z7zpveqqia9: undefined
   }

**Comment by damianog** [comment]
Maybe IE11 support isn't a priority nowadays

https://death-to-ie11.com/

**Comment by Christian-Oleson** [comment]
Can you confirm you are using server side? I know that WASM is not supported for IE11. Likewise, IE 11 support is dwindling from Microsoft over the next year

**Comment by danikf** [comment]
Blazor server side confirmed :-)
BTW - the only problem is with Date javascript constructor. Fix could be relatively easy.
D
