### ISSUE TITLE
Possible bug: MatAutocompelteList

### ISSUE THREAD

**Issue by KacperNiwczyk** [SamProf/MatBlazor#825]
**Describe the question**
Clearing value from MatAutocompleteList causes an exception: System.ArgumentNullException: Value cannot be null. (Parameter 'model')
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier..ctor(Object model, String fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at Microsoft.AspNetCore.Components.Forms.ValidationMessage`1.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)

**Blazorfiddle link**
https://blazorfiddle.com/s/m8zt1say

**Expected behavior**
Exception should not be thrown 

**Screenshots**
![image](https://user-images.githubusercontent.com/48415799/103461610-fe421280-4d1f-11eb-8fe7-d4e9cac4e0c9.png)

after I clicked out of this control 

![image](https://user-images.githubusercontent.com/48415799/103461626-1a45b400-4d20-11eb-84a7-46f11f5dae3b.png)

**Additional context**
Would appriciate any help. I'm not sure if I'm doing something wrong or this might be a bug

**Comment by Catter38** [comment]
Hey @KacperNiwczyk,

I just ran into the same issue.
But after checking the source of `MatAutocompleteList` I saw that the exception is actually caused by the `CustomStringSelector`.
After checking my code, I saw that I forgot to add the null-conditional operator.

Simply changing my code from

`CustomStringSelector="@(i => i.Name)"`

to

`CustomStringSelector="@(i => i?.Name)"`

fixed it for me.

Maybe you're having the same issue.

**Comment by KacperNiwczyk** [comment]
@Catter38 Nice call, I've resolved this by a property for setting my model attached to Autocomplete 

`private Client _selectedClient
{
    get
    {
        if (ReservationModel.Client == null)
        {
            return new Client()
            {
                CompanyName = "",
                Email = "",
                FirstName = "",
                LastName = "",
                PhoneNumber = "",
                Id = 0
            };
        }

        return ReservationModel.Client;

    }
    set => ReservationModel.Client = value;
}`

**Comment by Christian-Oleson** [comment]
@KacperNiwczyk ,
Is this still an issue then? If not, can you please close this?
